In [2]:
import scipy.io
import numpy as np
import torch




In [3]:



arr_cube = torch.randn(3, 20, 256, 256)
batch_size, dim1, dim2, dim3 = arr_cube.shape



In [9]:
z_ind_list = []
y_ind_list = []
x_ind_list = []
for i in range(arr_cube.shape[0]):
    # mpute the quantile for each batch separately
    quantile_value = arr_cube[i].quantile(0.9)
    # nd indices where the condition is met for each batch
    z_ind, y_ind, x_ind = torch.where(arr_cube[i] > quantile_value)
    # ore the indices for each batch
    z_ind_list.append(z_ind)
    y_ind_list.append(y_ind)
    x_ind_list.append(x_ind)

In [15]:

list_batch_indices = []
for batch_idx in range(arr_cube.shape[0]):
        batch_indices = torch.full((N,1), batch_idx, dtype = torch.long)
        list_batch_indices.append(batch_indices)
sp_indices = torch.cat(list_batch_indices)

IndexError: index 16 is out of bounds for dimension 0 with size 3

In [4]:
b_ind, z_ind, y_ind, x_ind = torch.where(arr_cube > arr_cube.quantile(0.9))

In [7]:
b_ind.shape

torch.Size([393216])

In [5]:
z_min, z_max =-5, 2.6
y_min, y_max = -51.2, 50.8
x_min, x_max = -51.2, 50.8
grid_size = 0.4

In [6]:
power_val = arr_cube[b_ind, z_ind, y_ind, x_ind].reshape(batch_size,-1).unsqueeze(-1)
B, N, C = power_val.shape
list_batch_indices = []
for batch_idx in range(B):
        batch_indices = torch.full((N,1), batch_idx, dtype = torch.long)
        list_batch_indices.append(batch_indices)
sp_indices = torch.cat(list_batch_indices)
power_val = power_val.view(B*N, C)
power_val.shape
z_pc_coord = ((z_min + z_ind * grid_size) - grid_size / 2).unsqueeze(-1)
y_pc_coord = ((y_min + y_ind * grid_size) - grid_size / 2).unsqueeze(-1)
x_pc_coord = ((x_min + x_ind * grid_size) - grid_size / 2).unsqueeze(-1)
sparse_rdr_cube = torch.cat((x_pc_coord, y_pc_coord, z_pc_coord, power_val), dim=-1).to(torch.float32)
sp_indices = torch.cat((sp_indices, z_ind.unsqueeze(-1), y_ind.unsqueeze(-1), x_ind.unsqueeze(-1)), dim = -1)

In [8]:
z_ind.unsqueeze(-1).shape

torch.Size([262144, 1])

In [10]:
for batch_idx in range(B):
        batch_indices = torch.full((N,1), batch_idx, dtype = torch.long)
        list_batch_indices.append(batch_indices)
sp_indices = torch.cat(list_batch_indices)
sp_indices.shape

torch.Size([786432, 1])

In [12]:
sp_indices.shape

torch.Size([262144, 4])

In [11]:
z_ind_new.shape

torch.Size([262144, 1])

In [12]:
z_ind_new.equal(z_ind.unsqueeze(-1))

True

In [14]:
x_coord

tensor([[-46.6000],
        [-40.6000],
        [-29.8000],
        ...,
        [ 41.0000],
        [ 42.6000],
        [ 45.4000]])

In [5]:
z_min, z_max =-5, 2.6
y_min, y_max = -51.2, 50.8
x_min, x_max = -51.2, 50.8
powfer_val = arr_cube[b_ind,z_ind, y_ind, x_ind].unsqueeze(-1)

z_pc_coord = ((z_min + z_ind * grid_size) - grid_size / 2).unsqueeze(-1)
y_pc_coord = ((y_min + y_ind * grid_size) - grid_size / 2).unsqueeze(-1)
x_pc_coord = ((x_min + x_ind * grid_size) - grid_size / 2).unsqueeze(-1)
sparse_rdr_cube = torch.cat((x_pc_coord, y_pc_coord, z_pc_coord, power_val), dim=-1).to(torch.float32)

x_coord, y_coord, z_coord = sparse_rdr_cube[:, 0:1], sparse_rdr_cube[:, 1:2], sparse_rdr_cube[:, 2:3]
list_batch_indices = []
for batch_idx in range(B):
    batch_indices = torch.full((N,1), batch_idx, dtype = torch.long)
    list_batch_indices.append(batch_indices)
sp_indices = torch.cat(list_batch_indices)
dtype = torch.float32

z_ind = torch.ceil((z_coord-z_min) / grid_size).long()
y_ind = torch.ceil((y_coord-y_min) / grid_size).long()
x_ind = torch.ceil((x_coord-x_min) / grid_size).long()
sp_indices = torch.cat((sp_indices, z_ind.unsqueeze(-1), y_ind.unsqueeze(-1), x_ind.unsqueeze(-1)), dim = -1)    

ValueError: not enough values to unpack (expected 3, got 2)

In [33]:
power_val = arr_cube[b_ind, z_ind, y_ind, x_ind].reshape(batch_size,-1).unsqueeze(-1)

grid_size = 0.4

# Adjusting the coordinate calculations to include the batch dimension
z_pc_coord = ((z_min + z_ind * grid_size) - grid_size / 2).unsqueeze(-1)
y_pc_coord = ((y_min + y_ind * grid_size) - grid_size / 2).unsqueeze(-1)
x_pc_coord = ((x_min + x_ind * grid_size) - grid_size / 2).unsqueeze(-1)

# Concatenating coordinates and power values, considering the batch dimension
sparse_rdr_cube = torch.cat((x_pc_coord, y_pc_coord, z_pc_coord, power_val), dim=-1).to(torch.float32)

In [36]:
power_val.shape

torch.Size([262144, 1])

In [30]:
list_batch_indices = []
for batch_idx in range(2):
            batch_indices = torch.full((131072,1), batch_idx, dtype = torch.long)
            list_batch_indices.append(batch_indices)
sp_indices = torch.cat(list_batch_indices)

In [34]:
sp_indices

tensor([[0],
        [0],
        [0],
        ...,
        [1],
        [1],
        [1]])

In [35]:
z_pc_coord.shape

torch.Size([262144, 1])

In [27]:
sparse_rdr_cube.shape

torch.Size([131072, 4])

In [25]:
arr_cube[b_ind, z_ind, y_ind, x_ind]

tensor([1.4788, 1.9477, 1.3865,  ..., 2.4471, 1.8429, 1.4591])

In [2]:

import scipy
import scipy.io
import numpy as np

radar_path = '/mnt/data/DataSet/K-Radar/2/radar_zyx_cube/cube_00001.mat'
mat_data = scipy.io.loadmat(radar_path)

In [5]:
mat_data['arr_zyx'].shape

(150, 400, 250)