In [1]:
import os
import os.path as osp
import numpy as np
import glob

In [19]:
data = np.load('/mnt/data/DataSet/K-RadarOOC/train/1/semantic_occupancy_gt_fov/occupancy_gt_with_semantic_fov499.npy')

In [20]:
np.unique(data[:,2],return_counts=True)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13]),
 array([2637, 3675, 3260, 3148, 1765,  951,  755,  698,  544,  507,  437,
         373,  300,  305]))

In [3]:
data.shape

(15464, 4)

In [12]:
data[:,2].min()

4

In [13]:
data[:,2].max()

19

In [28]:
np.min(data[:,0])

6

In [29]:
np.max(data[:,1]),np.min(data[:,1])

(63, 3)

In [2]:
clips = sorted(os.listdir("/mnt/data/DataSet/K-RadarOOC/train"),key=lambda x:int(x))

ValueError: invalid literal for int() with base 10: 'vis_lidar_32_pc'

In [5]:
import glob
import numpy as np
dict = {0:0,1:0,2:0}

for seq in [3,15,23,55,22,1,2,4,6,7,8,9,10,11,12,13,14,16,17,18,19,20,27,56]:
    files = glob.glob("/mnt/data/DataSet/K-RadarOOC/train/{}/semantic_occupancy_gt/*.npy".format(seq),recursive=True)
    for f in files:
        data = np.load(f)
        a,b = np.unique(data[:,3],return_counts=True)
        total = 128*128*20
        for i in range(len(a)):
            if a[i] == 1:
                dict[1] += b[i]
                total -= b[i]
            else:
                dict[2] += b[i]
                total -= b[i]
        dict[0] += total

In [6]:
dict

{0: 4628412772, 1: 369940410, 2: 14167778}

'tesseract_00001.mat'

In [ ]:
9503618838,459142461

In [10]:
10461682+ 6350264+37961+47173+121097+9904+737

17028818

In [2]:
8925533

8925533

In [3]:
5402424+31198+39551+110245+8742+708

5592868

In [5]:
dict

{0: 13904425433,
 1: 377126668,
 2: 8962736,
 3: 5410936,
 4: 31200,
 5: 39551,
 6: 110315,
 7: 8742,
 8: 708,
 9: 0,
 10: 0}

In [6]:
np.array([13904425433,377126668,8962736 + 5410936+31200+39551+110315+8742+708])

array([13904425433,   377126668,    14564188])

In [13]:
np.log(np.array([5737271769,   60146880,    2315175]))

array([22.47024963, 17.91230013, 14.65499584])

In [25]:
3091677700/1000,5089575/1000,181124/1000,117815/1000

(3091677.7, 5089.575, 181.124, 117.815)

In [19]:
np.unique(data[:,3],return_counts=True)

(array([1, 2, 3]), array([36260,  2789,  1780]))

In [20]:
512*512*40

10485760